//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlideTools.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;bool&gt;1|True|Yes|^OK|Up|Good|Fine)).
        /// </summary>
        internal static string rxBoolTrue {
            get {
                return ResourceManager.GetString("rxBoolTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;field&gt;\{(?&lt;name&gt;[^\}]+)\}).
        /// </summary>
        internal static string rxEmbeddedFieldName {
            get {
                return ResourceManager.GetString("rxEmbeddedFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;name&gt;[a-z]+)\s*(?&lt;operator&gt;(=|\&lt;\&gt;|\&lt;=|\&gt;=|\&lt;|\&gt;))\s*(?&lt;value&gt;(&apos;[^&apos;]+&apos;|\&quot;[^&apos;\&quot;]+\&quot;|[a-z]+|[0-9\.-]+|\{[^\}]+\}))\s*).
        /// </summary>
        internal static string rxExpressionPairs {
            get {
                return ResourceManager.GetString("rxExpressionPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?s:line\s+(?&lt;line&gt;\d+).*?position\s+(?&lt;position&gt;\d+))).
        /// </summary>
        internal static string rxJsonErrorLinePosition {
            get {
                return ResourceManager.GetString("rxJsonErrorLinePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;numberWithUnit&gt;(?&lt;number&gt;-{0,1}[0-9]+(\.[0-9]+){0,1})(\s*(?&lt;unit&gt;[a-z]+)){1})).
        /// </summary>
        internal static string rxNumberWithUnit {
            get {
                return ResourceManager.GetString("rxNumberWithUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?&lt;pre&gt;.*?)(?&lt;seed&gt;\d+)(?&lt;post&gt;.*)$.
        /// </summary>
        internal static string rxNumericalSeed {
            get {
                return ResourceManager.GetString("rxNumericalSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlideTools Processor for PowerPoint
        ///
        ///Syntax:
        ///SlideTools.exe  /infile:{Filename}
        ///                /action:{ActionName}
        ///                [/configfile:{Filename}]
        ///                [/workingpath:{Pathname}]
        ///                [/outfile:{Filename}]
        ///                [/wait]
        ///
        ///    action          -   Name of the action to perform. Following are the valid
        ///                        available actions in this version.
        ///                        SlideReport - Create and output a report of the slides
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
    }
}
